stages:
  - ci

master-72:
  stage: ci
  trigger:
    include: build/gitlab/master-72.yml
    strategy: depend

master-73:
  stage: ci
  trigger:
    include: build/gitlab/master-73.yml
    strategy: depend

master-74:
  stage: ci
  trigger:
    include: build/gitlab/master-74.yml
    strategy: depend

t310-74:
  stage: ci
  trigger:
    include: build/gitlab/t310-74.yml
    strategy: depend

variables:
  IMAGE: "composer:2"

lint:
  stage: ci
  image: $IMAGE
  script:
    - composer install
    - composer run ci:lint:yaml
    - composer run ci:lint:typoscript


