stages:
  - build_ci
  - ci

variables:
  IMAGE: "composer:2"

build-dev:
  stage: build_ci
  image: $IMAGE
  script:
    - echo "Build started for PHP Version $PHP with TYPO3 $TYPO3"
    - composer install

  artifacts:
    name: TYPO3
    paths:
      - .build/
      - ./composer.lock
    expire_in: '1h'

cgl:
  stage: ci
  dependencies:
    - build-dev
  image: composer:2
  script:
    - composer run ci:cgl:check

lint:
  stage: ci
  dependencies:
    - build-dev
  image: composer:2
  script:
    - composer run ci:lint:php
    - composer run ci:lint:yaml
    - composer run ci:lint:typoscript

stan:
  stage: ci
  dependencies:
    - build-dev
  image: composer:2
  script:
    - composer run ci:stan

